source 'https://rubygems.org'

ruby '2.2.3'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.5'
gem 'pg'
# Use sqlite3 as the database for Active Record
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes

gem 'jquery-rails'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.

# login
gem 'devise'
gem 'devise-bootstrap-views'

# Use ActiveModel has_secure_password
gem 'bcrypt', '~> 3.1.7'

gem 'puma'

gem 'rack-cors', :require => 'rack/cors'

group :development do
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem "better_errors"
  gem "binding_of_caller"
  gem 'meta_request'
end

group :development, :test do
  gem 'byebug'
  gem 'quiet_assets'
  gem 'faker' # https://github.com/stympy/faker
  gem 'mailcatcher'
end

group :production, :staging do
  gem "rails_12factor"
  gem "rails_stdout_logging"
  gem "rails_serve_static_assets"
end

gem 'pg_search'
